[project]
name = "ai-a11y-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "esprima>=4.0.1",
    "openai-agents>=0.5.0",
    "pydantic>=2.12.4",
    "typer>=0.20.0",
]
